language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  app: weparorratebeer
  api_key:
    secure: YaIlXMJs+e22HMCXrhaGAkrhjIiUUZY2F197fC60Ib48zY33fhuriZd956eGGKZtXhDwPM34u90qvkRLGCDJCEzrJQyJdSdcE6zqQqggljRtHTNLL4MVVrwEDpNWX2dS3iftXlVyIu9T+vm3qYSwiwWuP5xbuC/3eZLPNBqWwYu+f9l6O5JRoHuI6GTNA2fxdpGKQJIv5n+D7qUA2sWQsPXDvoCPuKadp0Too4QnYz+IBQSL8OAZ8eSHTpRKzf5efRso4G6wbO0vchPVM4nIy8z31bu8KTlxKNxVdpyCrCwzda0FIItefX/CfiwFnlgmJ42Z2YEf2phVPbWL+hPzW8Ms8i2jumZkWaKPSGADZ4rhI6eknLeE7vt83C5WwcI/LOldz3DwR+jwQUeoftoPJ0mWDleiUqSsQW0Bjo0Pl6Dwq6dEbXGA2vrMXYq1DntKjSUb55AwaFmd2+jYHsVREABTXP4ZHuDK5osrBQI40PMi9cnJAKCSc4QWmb8mUZY+Zh5+2KyvEnPNwp0HC74eQpcaXpMq3V7Fwaqu2VB8+QGg6N6s93K5SQQznbDvR4frfkV+saXhs4NeScZOuXjqeudz09NjZ2roRDYuoAYFDv3z12CCFff4uAtw+Gej8JScYNsycj2XAnUGqbqKhxDCKFDTxPaWmzxwEuhOvkbm7hw=
  run: rails db:migrate
env:
  global:
    secure: Wy1Od8HC3HGz+QEdG+Y/wJgviVTMgtyrex8T2wZr4dYYV0kcdrk6gc89V05QqXOEeOhyOAft08EA7vMXk6C4aC8fKg8Kt7MBveSZx2ems7uDkFhAAh/3HOZaofvPcYffnrGAkydexOmDerfDBlW26sDvp0wtATo1cXCNfHdEz2cWMExLEYwUW9bnPKg0q7sEez6j9XOXM6qpef/jSFtUUScOW4/1APApQxtIbP/CkqmucrXaMtJ2R8rWbOFEGghNXHeeuBxmiBsca8ISkVkxWHlyYdh5g+B78xdmG2hRr5woYCmeT6bWnGhGeChA6txbuNeBkVB/bJ44TlNEayAeQRY+sR0CUfDfkbcUKR+gTpZXnVrFZ/MOB42xIhG/sRJqHdYIftOUqtS2dbWhAJPoX6IpsqGrjyN3vrm1NIKPasUUw8bOQcjQz/7ef0LN+MYT3bbQraLDTXSWTRLquI1CQBEHXM16QzldCjmEQEg7KbqxvOVtpjA5xoGl2ZmEgqn1t1MdgLFYh8sq+AKpBlbuWJktDUSOrgEb8NpjjcoFkmOJS94jx6ocsza3p0n/W7n1K7dIBrVm4kFeTp1eIPv94qg+d3atiUfYisPulqQsjINtEDwUK/xb0vGOAfToojy9TI4VNWg5su3qnjxT+B1M2KTULQnIf7KCao4Q4JamBig=
