language: ruby
rvm:
- 2.5.1
script:
- bundle exec rails db:migrate
- bundle exec rspec -fd spec
deploy:
  provider: heroku
  app: weparorratebeer
  api_key:
    secure: YaIlXMJs+e22HMCXrhaGAkrhjIiUUZY2F197fC60Ib48zY33fhuriZd956eGGKZtXhDwPM34u90qvkRLGCDJCEzrJQyJdSdcE6zqQqggljRtHTNLL4MVVrwEDpNWX2dS3iftXlVyIu9T+vm3qYSwiwWuP5xbuC/3eZLPNBqWwYu+f9l6O5JRoHuI6GTNA2fxdpGKQJIv5n+D7qUA2sWQsPXDvoCPuKadp0Too4QnYz+IBQSL8OAZ8eSHTpRKzf5efRso4G6wbO0vchPVM4nIy8z31bu8KTlxKNxVdpyCrCwzda0FIItefX/CfiwFnlgmJ42Z2YEf2phVPbWL+hPzW8Ms8i2jumZkWaKPSGADZ4rhI6eknLeE7vt83C5WwcI/LOldz3DwR+jwQUeoftoPJ0mWDleiUqSsQW0Bjo0Pl6Dwq6dEbXGA2vrMXYq1DntKjSUb55AwaFmd2+jYHsVREABTXP4ZHuDK5osrBQI40PMi9cnJAKCSc4QWmb8mUZY+Zh5+2KyvEnPNwp0HC74eQpcaXpMq3V7Fwaqu2VB8+QGg6N6s93K5SQQznbDvR4frfkV+saXhs4NeScZOuXjqeudz09NjZ2roRDYuoAYFDv3z12CCFff4uAtw+Gej8JScYNsycj2XAnUGqbqKhxDCKFDTxPaWmzxwEuhOvkbm7hw=
  run: "rails db:migrate"